display_name = "Catppuccin Latte"

[vars]
ghostty = "Catppuccin Latte"

[gnome]
gtk_theme = "Catppuccin-Latte-Standard-Blue-Light"
shell_theme = "Catppuccin-Latte-Standard-Blue-Light"
icon_theme = "Papirus-Light"
accent_color = "blue"
color_scheme = "prefer-light"

[palette]
base     = "#eff1f5"
mantle   = "#e6e9ef"
surface  = "#ccd0da"
overlay  = "#9ca0b0"
muted    = "#bcc0cc"
text     = "#4c4f69"
subtext  = "#5c5f77"
red      = "#d20f39"
orange   = "#fe640b"
yellow   = "#df8e1d"
green    = "#40a02b"
teal     = "#179299"
sky      = "#04a5e5"
sapphire = "#209fb5"
blue     = "#1e66f5"
mauve    = "#ea76cb"

[colors]
highlight       = "blue"
secondary       = "subtext"
title           = "text"
hi_fg           = "blue"
selected_fg     = "blue"
graph_text      = "subtext"
proc_misc       = "subtext"
cpu_box         = "mauve"
mem_box         = "green"
net_box         = "red"
proc_box        = "blue"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "teal"
cpu_mid         = "sapphire"
cpu_end         = "red"
free_start      = "mauve"
free_mid        = "subtext"
free_end        = "blue"
cached_start    = "sapphire"
cached_mid      = "blue"
cached_end      = "red"
available_start = "orange"
available_mid   = "red"
available_end   = "red"
used_start      = "green"
used_mid        = "teal"
used_end        = "red"
download_start  = "teal"
download_mid    = "blue"
download_end    = "red"
upload_start    = "green"
upload_mid      = "teal"
upload_end      = "red"
process_start   = "sapphire"
process_mid     = "subtext"
process_end     = "mauve"
replace_mode    = "teal"
visual_mode     = "overlay"
dir_fg          = "blue"
git_fg          = "mauve"
time_fg         = "yellow"
