display_name = "Poimandres"

[vars]
ghostty = "Poimandres"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "teal"
color_scheme = "prefer-dark"

[palette]
base     = "#1b1e28"
mantle   = "#151720"
surface  = "#303340"
overlay  = "#555970"
muted    = "#767c9d"
text     = "#e4f0fb"
subtext  = "#a6accd"
red      = "#d0679d"
orange   = "#fcc5e9"
yellow   = "#fffac2"
green    = "#5de4c7"
teal     = "#5de4c7"
sky      = "#add7ff"
sapphire = "#89ddff"
blue     = "#89ddff"
mauve    = "#fcc5e9"

[colors]
highlight       = "green"
secondary       = "sky"
title           = "subtext"
hi_fg           = "green"
selected_fg     = "text"
graph_text      = "subtext"
proc_misc       = "sky"
cpu_box         = "green"
mem_box         = "sapphire"
net_box         = "red"
proc_box        = "sky"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "sapphire"
cpu_start       = "green"
cpu_mid         = "sapphire"
cpu_end         = "red"
free_start      = "green"
free_mid        = "sapphire"
free_end        = "sky"
cached_start    = "green"
cached_mid      = "teal"
cached_end      = "sky"
available_start = "green"
available_mid   = "sapphire"
available_end   = "red"
used_start      = "green"
used_mid        = "sapphire"
used_end        = "red"
download_start  = "green"
download_mid    = "sapphire"
download_end    = "sky"
upload_start    = "teal"
upload_mid      = "sapphire"
upload_end      = "red"
process_start   = "green"
process_mid     = "sapphire"
process_end     = "sky"
replace_mode    = "sapphire"
visual_mode     = "overlay"
dir_fg          = "green"
git_fg          = "sapphire"
time_fg         = "muted"
