display_name = "Solarized Dark"

[vars]
ghostty = "Builtin Solarized Dark"

[nvim]
colorscheme = "solarized"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "teal"
color_scheme = "prefer-dark"

[palette]
base     = "#002b36"
mantle   = "#073642"
surface  = "#073642"
overlay  = "#586e75"
muted    = "#657b83"
text     = "#839496"
subtext  = "#93a1a1"
red      = "#dc322f"
orange   = "#cb4b16"
yellow   = "#b58900"
green    = "#859900"
teal     = "#2aa198"
sky      = "#268bd2"
sapphire = "#268bd2"
blue     = "#268bd2"
mauve    = "#6c71c4"

[colors]
highlight       = "blue"
secondary       = "teal"
title           = "subtext"
hi_fg           = "blue"
selected_fg     = "subtext"
graph_text      = "subtext"
proc_misc       = "teal"
cpu_box         = "blue"
mem_box         = "green"
net_box         = "red"
proc_box        = "teal"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "green"
cpu_mid         = "teal"
cpu_end         = "blue"
free_start      = "teal"
free_mid        = "blue"
free_end        = "mauve"
cached_start    = "green"
cached_mid      = "teal"
cached_end      = "blue"
available_start = "green"
available_mid   = "yellow"
available_end   = "orange"
used_start      = "green"
used_mid        = "yellow"
used_end        = "red"
download_start  = "teal"
download_mid    = "blue"
download_end    = "mauve"
upload_start    = "green"
upload_mid      = "teal"
upload_end      = "blue"
process_start   = "green"
process_mid     = "teal"
process_end     = "blue"
replace_mode    = "teal"
visual_mode     = "overlay"
dir_fg          = "blue"
git_fg          = "teal"
time_fg         = "yellow"
