display_name = "Hackerman"

[vars]
ghostty = "Hackerman"

[nvim]
strategy = "luafile"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "green"
color_scheme = "prefer-dark"

[palette]
base     = "#0B0C16"
mantle   = "#08090f"
surface  = "#6a6e95"
overlay  = "#4a4d6a"
muted    = "#6a6e95"
text     = "#ddf7ff"
subtext  = "#85E1FB"
red      = "#50f872"
orange   = "#85ff9d"
yellow   = "#50f7d4"
green    = "#4fe88f"
teal     = "#7cf8f7"
sky      = "#d1fffe"
sapphire = "#829dd4"
blue     = "#c4d2ed"
mauve    = "#86a7df"

[colors]
highlight       = "red"
secondary       = "teal"
title           = "subtext"
hi_fg           = "red"
selected_fg     = "text"
graph_text      = "subtext"
proc_misc       = "teal"
cpu_box         = "red"
mem_box         = "green"
net_box         = "teal"
proc_box        = "sapphire"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "green"
cpu_mid         = "teal"
cpu_end         = "red"
free_start      = "teal"
free_mid        = "green"
free_end        = "red"
cached_start    = "teal"
cached_mid      = "sky"
cached_end      = "red"
available_start = "green"
available_mid   = "yellow"
available_end   = "red"
used_start      = "green"
used_mid        = "teal"
used_end        = "red"
download_start  = "teal"
download_mid    = "sapphire"
download_end    = "red"
upload_start    = "green"
upload_mid      = "teal"
upload_end      = "red"
process_start   = "green"
process_mid     = "teal"
process_end     = "sapphire"
error_status    = "orange"
replace_mode    = "yellow"
visual_mode     = "sapphire"
dir_fg          = "red"
git_fg          = "teal"
time_fg         = "subtext"
