# foot theme written by themeSwitcher.

[cursor]
color={{background_strip}} {{accent_strip}}

[colors]
foreground={{foreground_strip}}
background={{background_strip}}
selection-foreground={{selected_fg_strip}}
selection-background={{selected_bg_strip}}

regular0={{background_strip}}
regular1={{red_strip}}
regular2={{green_strip}}
regular3={{yellow_strip}}
regular4={{blue_strip}}
regular5={{mauve_strip}}
regular6={{teal_strip}}
regular7={{foreground_strip}}

bright0={{muted_strip}}
bright1={{red_strip}}
bright2={{green_strip}}
bright3={{orange_strip}}
bright4={{sapphire_strip}}
bright5={{mauve_strip}}
bright6={{sky_strip}}
bright7={{foreground_strip}}
