# Mako theme written by themeSwitcher.

font=Inter 11
background-color={{background}}
text-color={{foreground}}
border-color={{accent}}
progress-color=over {{surface}}
border-size=2
border-radius=4
default-timeout=5000
max-icon-size=48
padding=12

[urgency=low]
border-color={{overlay}}

[urgency=high]
border-color={{red}}
default-timeout=0
