display_name = "Rosé Pine"

[vars]
ghostty = "Rose Pine"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "pink"

[palette]
base     = "#191724"
mantle   = "#1f1d2e"
surface  = "#524f67"
overlay  = "#6e6a86"
muted    = "#403d52"
text     = "#e0def4"
subtext  = "#908caa"
red      = "#eb6f92"
orange   = "#f6c177"
yellow   = "#f6c177"
green    = "#31748f"
teal     = "#9ccfd8"
sky      = "#9ccfd8"
sapphire = "#31748f"
blue     = "#31748f"
mauve    = "#c4a7e7"

[colors]
highlight       = "mauve"
secondary       = "teal"
title           = "subtext"
hi_fg           = "text"
selected_fg     = "orange"
graph_text      = "teal"
meter_bg        = "teal"
proc_misc       = "mauve"
cpu_box         = "red"
mem_box         = "green"
net_box         = "mauve"
proc_box        = "red"
div_line        = "overlay"
temp_start      = "red"
temp_mid        = "orange"
cpu_start       = "teal"
cpu_mid         = "green"
cpu_end         = "red"
free_start      = "red"
free_mid        = "mauve"
free_end        = "red"
cached_start    = "mauve"
cached_mid      = "mauve"
cached_end      = "mauve"
available_start = "green"
available_mid   = "green"
available_end   = "green"
used_start      = "red"
used_mid        = "red"
used_end        = "red"
download_start  = "green"
download_mid    = "teal"
download_end    = "teal"
upload_start    = "red"
upload_mid      = "red"
upload_end      = "red"
process_start   = "green"
process_mid     = "teal"
process_end     = "teal"
success_status  = "teal"
replace_mode    = "overlay"
visual_mode     = "red"
dir_fg          = "mauve"
git_fg          = "green"
time_fg         = "orange"
