display_name = "Miasma"

[vars]
ghostty = "Miasma"

[nvim]
strategy = "luafile"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "olive"
color_scheme = "prefer-dark"

[palette]
base     = "#222222"
mantle   = "#111111"
surface  = "#666666"
overlay  = "#444444"
muted    = "#666666"
text     = "#c2c2b0"
subtext  = "#d7c483"
red      = "#685742"
orange   = "#bb7744"
yellow   = "#b36d43"
green    = "#5f875f"
teal     = "#c9a554"
sky      = "#d7c483"
sapphire = "#78824b"
blue     = "#78824b"
mauve    = "#bb7744"

[colors]
highlight       = "sapphire"
secondary       = "teal"
title           = "subtext"
hi_fg           = "sapphire"
selected_fg     = "subtext"
graph_text      = "text"
proc_misc       = "teal"
cpu_box         = "sapphire"
mem_box         = "green"
net_box         = "orange"
proc_box        = "teal"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "teal"
temp_end        = "orange"
cpu_start       = "green"
cpu_mid         = "sapphire"
cpu_end         = "orange"
free_start      = "green"
free_mid        = "teal"
free_end        = "orange"
cached_start    = "green"
cached_mid      = "teal"
cached_end      = "orange"
available_start = "green"
available_mid   = "teal"
available_end   = "orange"
used_start      = "green"
used_mid        = "sapphire"
used_end        = "orange"
download_start  = "green"
download_mid    = "teal"
download_end    = "orange"
upload_start    = "teal"
upload_mid      = "sapphire"
upload_end      = "orange"
process_start   = "green"
process_mid     = "teal"
process_end     = "orange"
error_status    = "orange"
replace_mode    = "teal"
visual_mode     = "sapphire"
dir_fg          = "teal"
git_fg          = "green"
time_fg         = "subtext"
