# [metadata]
# name = "miguel's config"
# author = "miguel"
# origin_url = "https://github.com/EdenEast/nightfox.nvim"

"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory $git_branch$git_status $character"""

right_format = "$time"

palette = "one-dark-pro"

[palettes.one-dark-pro]
error_status = "#e06c75"
success_status = "#3f534f"
replace_mode = "#7ec7d1"
visual_mode = "#abb2bf"
bg = "#282c34"
dir_fg = "#61afef"
git_fg = "#98c379"
time_fg = "#edd2a1"

[directory]
style = "fg:dir_fg bg:bg"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "

[git_branch]
symbol = ""
style = "bg:bg"
format = 'at [[$symbol $branch](fg:git_fg bg:bg)]($style)'

[git_status]
style = "bg:bg"
format = '[[( $all_status$ahead_behind)](fg:git_fg bg:bg)]($style)'

[character]
disabled = false
success_symbol = '[>](bold fg:success_status)'
error_symbol = '[>](bold fg:error_status)'
vimcmd_symbol = '[<](bold fg:success_status)'
vimcmd_replace_one_symbol = '[<](bold fg:replace_mode)'
vimcmd_replace_symbol = '[<](bold fg:replace_mode)'
vimcmd_visual_symbol = '[<](bold fg:visual_mode)'

[fill]
symbol = ""

[time]
disabled = false
style = "fg:time_fg bg:bg"
format = "[$time]($style)"
time_format = "%H:%M"
