display_name = "Lumon"

[vars]
ghostty = "Lumon"

[nvim]
strategy = "luafile"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "teal"
color_scheme = "prefer-dark"

[palette]
base     = "#16242d"
mantle   = "#0f1a21"
surface  = "#304860"
overlay  = "#1b2d40"
muted    = "#304860"
text     = "#d6e2ee"
subtext  = "#b4e4f6"
red      = "#4d86b0"
orange   = "#73a6cb"
yellow   = "#6fa4c9"
green    = "#5e95bc"
teal     = "#6fb8e3"
sky      = "#d1eef8"
sapphire = "#8bc9eb"
blue     = "#f2fcff"
mauve    = "#b1d8ee"

[colors]
highlight       = "teal"
secondary       = "sapphire"
title           = "subtext"
hi_fg           = "teal"
selected_fg     = "blue"
graph_text      = "subtext"
proc_misc       = "sapphire"
cpu_box         = "teal"
mem_box         = "green"
net_box         = "sapphire"
proc_box        = "subtext"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "teal"
temp_end        = "sapphire"
cpu_start       = "green"
cpu_mid         = "teal"
cpu_end         = "sapphire"
free_start      = "teal"
free_mid        = "sapphire"
free_end        = "blue"
cached_start    = "green"
cached_mid      = "teal"
cached_end      = "sapphire"
available_start = "green"
available_mid   = "teal"
available_end   = "sapphire"
used_start      = "green"
used_mid        = "teal"
used_end        = "sapphire"
download_start  = "green"
download_mid    = "teal"
download_end    = "blue"
upload_start    = "teal"
upload_mid      = "sapphire"
upload_end      = "blue"
process_start   = "green"
process_mid     = "teal"
process_end     = "sapphire"
error_status    = "sapphire"
success_status  = "subtext"
replace_mode    = "surface"
visual_mode     = "mauve"
dir_fg          = "teal"
git_fg          = "sapphire"
time_fg         = "subtext"
