display_name = "One Dark Pro"

[vars]
ghostty = "One Half Dark"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "One-Dark"
shell_theme = "One-Dark"
icon_theme = "Papirus-Dark"
accent_color = "blue"

[palette]
base     = "#282c34"
mantle   = "#21252b"
surface  = "#2c313c"
overlay  = "#3e4452"
muted    = "#5c6370"
text     = "#abb2bf"
subtext  = "#abb2bf"
red      = "#e06c75"
orange   = "#d19a66"
yellow   = "#e5c07b"
green    = "#98c379"
teal     = "#56b6c2"
sky      = "#61afef"
sapphire = "#61afef"
blue     = "#61afef"
mauve    = "#c678dd"

[colors]
highlight       = "blue"
secondary       = "yellow"
title           = "text"
hi_fg           = "blue"
selected_fg     = "text"
graph_text      = "text"
proc_misc       = "blue"
cpu_box         = "muted"
mem_box         = "muted"
net_box         = "muted"
proc_box        = "muted"
div_line        = "muted"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "green"
cpu_mid         = "yellow"
cpu_end         = "red"
free_start      = "green"
free_mid        = "yellow"
free_end        = "red"
cached_start    = "green"
cached_mid      = "yellow"
cached_end      = "red"
available_start = "green"
available_mid   = "yellow"
available_end   = "red"
used_start      = "green"
used_mid        = "yellow"
used_end        = "red"
download_start  = "green"
download_mid    = "yellow"
download_end    = "red"
upload_start    = "green"
upload_mid      = "yellow"
upload_end      = "red"
process_start   = "green"
process_mid     = "yellow"
process_end     = "red"
replace_mode    = "teal"
visual_mode     = "text"
dir_fg          = "blue"
git_fg          = "green"
time_fg         = "yellow"
