display_name = "Retro 82"

[vars]
ghostty = "Retro 82"

[nvim]
strategy = "luafile"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "orange"
color_scheme = "prefer-dark"

[palette]
base     = "#05182e"
mantle   = "#00172e"
surface  = "#134e5a"
overlay  = "#0d3545"
muted    = "#134e5a"
text     = "#f6dcac"
subtext  = "#a7c9c6"
red      = "#f85525"
orange   = "#e97b3c"
yellow   = "#faa968"
green    = "#028391"
teal     = "#3f8f8a"
sky      = "#8cbfb8"
sapphire = "#028391"
blue     = "#3f8f8a"
mauve    = "#faa968"

[colors]
highlight       = "yellow"
secondary       = "teal"
title           = "subtext"
hi_fg           = "yellow"
selected_fg     = "text"
graph_text      = "subtext"
proc_misc       = "sky"
cpu_box         = "yellow"
mem_box         = "green"
net_box         = "red"
proc_box        = "teal"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "orange"
cpu_start       = "green"
cpu_mid         = "yellow"
cpu_end         = "red"
free_start      = "teal"
free_mid        = "yellow"
free_end        = "orange"
cached_start    = "green"
cached_mid      = "teal"
cached_end      = "sky"
available_start = "green"
available_mid   = "orange"
available_end   = "red"
used_start      = "green"
used_mid        = "yellow"
used_end        = "red"
download_start  = "teal"
download_mid    = "yellow"
download_end    = "red"
upload_start    = "green"
upload_mid      = "orange"
upload_end      = "red"
process_start   = "green"
process_mid     = "teal"
process_end     = "yellow"
replace_mode    = "orange"
visual_mode     = "teal"
dir_fg          = "yellow"
git_fg          = "teal"
time_fg         = "subtext"
