display_name = "Tokyo Night"

[vars]
ghostty = "TokyoNight"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Tokyonight-Dark-BL"
shell_theme = "Tokyonight-Dark-BL"
icon_theme = "Papirus-Dark"
accent_color = "purple"

[palette]
base     = "#1a1b26"
mantle   = "#16161e"
surface  = "#414868"
overlay  = "#565f89"
muted    = "#565f89"
text     = "#cdc9c2"
subtext  = "#cfc9c2"
red      = "#f7768e"
orange   = "#ff9e64"
yellow   = "#e0af68"
green    = "#9ece6a"
teal     = "#73daca"
sky      = "#7dcfff"
sapphire = "#2ac3de"
blue     = "#7aa2f7"
mauve    = "#bb9af7"

[colors]
highlight       = "sky"
secondary       = "mauve"
title           = "subtext"
hi_fg           = "sky"
selected_fg     = "subtext"
graph_text      = "subtext"
proc_misc       = "sky"
cpu_box         = "muted"
mem_box         = "muted"
net_box         = "muted"
proc_box        = "muted"
div_line        = "muted"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "green"
cpu_mid         = "yellow"
cpu_end         = "red"
free_start      = "green"
free_mid        = "yellow"
free_end        = "red"
cached_start    = "green"
cached_mid      = "yellow"
cached_end      = "red"
available_start = "green"
available_mid   = "yellow"
available_end   = "red"
used_start      = "green"
used_mid        = "yellow"
used_end        = "red"
download_start  = "green"
download_mid    = "yellow"
download_end    = "red"
upload_start    = "green"
upload_mid      = "yellow"
upload_end      = "red"
process_start   = "green"
process_mid     = "yellow"
process_end     = "red"
replace_mode    = "yellow"
visual_mode     = "muted"
dir_fg          = "sky"
git_fg          = "teal"
time_fg         = "subtext"
