display_name = "Monokai Pro Ristretto"

[vars]
ghostty = "Monokai Pro Ristretto"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "orange"

[palette]
base     = "#2c2421"
mantle   = "#241c19"
surface  = "#3d2f2a"
overlay  = "#5b4a45"
muted    = "#72696a"
text     = "#e6d9db"
subtext  = "#e6d9db"
red      = "#fd6883"
orange   = "#f38d70"
yellow   = "#f9cc6c"
green    = "#adda78"
teal     = "#85dacc"
sky      = "#b3e8dd"
sapphire = "#a8a9eb"
blue     = "#a8a9eb"
mauve    = "#c5c6f0"

[colors]
highlight       = "red"
secondary       = "yellow"
title           = "text"
hi_fg           = "red"
selected_fg     = "text"
graph_text      = "text"
proc_misc       = "green"
cpu_box         = "overlay"
mem_box         = "overlay"
net_box         = "overlay"
proc_box        = "overlay"
div_line        = "muted"
temp_start      = "sapphire"
temp_mid        = "orange"
cpu_start       = "green"
cpu_mid         = "yellow"
cpu_end         = "red"
free_start      = "overlay"
free_mid        = "green"
free_end        = "green"
cached_start    = "overlay"
cached_mid      = "teal"
cached_end      = "sky"
available_start = "overlay"
available_mid   = "yellow"
available_end   = "yellow"
used_start      = "overlay"
used_mid        = "mauve"
used_end        = "red"
download_start  = "surface"
download_mid    = "sapphire"
download_end    = "mauve"
upload_start    = "surface"
upload_mid      = "red"
upload_end      = "red"
process_start   = "green"
process_mid     = "yellow"
process_end     = "red"
replace_mode    = "yellow"
visual_mode     = "sapphire"
dir_fg          = "orange"
git_fg          = "muted"
time_fg         = "text"
