display_name = "Gruvbox"

[vars]
ghostty = "Gruvbox Dark"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Gruvbox-Dark-BL"
shell_theme = "Gruvbox-Dark-BL"
icon_theme = "Papirus-Dark"
accent_color = "yellow"

[palette]
base     = "#282828"
mantle   = "#1d2021"
surface  = "#3c3836"
overlay  = "#504945"
muted    = "#282828"
text     = "#ebdbb2"
subtext  = "#a89984"
red      = "#cc241d"
orange   = "#d65d0e"
yellow   = "#d79921"
green    = "#98971a"
teal     = "#458588"
sky      = "#83a598"
sapphire = "#83a598"
blue     = "#458588"
mauve    = "#b16286"

[colors]
foreground      = "subtext"
highlight       = "yellow"
secondary       = "yellow"
title           = "text"
hi_fg           = "yellow"
selected_bg     = "base"
selected_fg     = "yellow"
graph_text      = "overlay"
proc_misc       = "green"
cpu_box         = "subtext"
mem_box         = "subtext"
net_box         = "subtext"
proc_box        = "subtext"
div_line        = "overlay"
temp_start      = "teal"
temp_mid        = "mauve"
cpu_start       = "green"
cpu_mid         = "yellow"
cpu_end         = "red"
free_start      = "green"
free_mid        = ""
free_end        = "green"
cached_start    = "teal"
cached_mid      = ""
cached_end      = "sky"
available_start = "yellow"
available_mid   = ""
available_end   = "yellow"
used_start      = "teal"
used_mid        = ""
used_end        = "red"
download_start  = "teal"
download_mid    = "mauve"
download_end    = "mauve"
upload_start    = "mauve"
upload_mid      = "mauve"
upload_end      = "mauve"
process_start   = "green"
process_mid     = "yellow"
process_end     = "red"
replace_mode    = "teal"
visual_mode     = "mauve"
dir_fg          = "yellow"
git_fg          = "sky"
time_fg         = "yellow"
