display_name = "Ethereal"

[vars]
ghostty = "Ethereal"

[nvim]
strategy = "luafile"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "purple"
color_scheme = "prefer-dark"

[palette]
base     = "#060B1E"
mantle   = "#040817"
surface  = "#6d7db6"
overlay  = "#4a5490"
muted    = "#6d7db6"
text     = "#ffcead"
subtext  = "#F99957"
red      = "#ED5B5A"
orange   = "#faaaa9"
yellow   = "#E9BB4F"
green    = "#92a593"
teal     = "#a3bfd1"
sky      = "#dfeaf0"
sapphire = "#7d82d9"
blue     = "#c2c4f0"
mauve    = "#c89dc1"

[colors]
highlight       = "sapphire"
secondary       = "mauve"
title           = "text"
hi_fg           = "sapphire"
selected_fg     = "text"
graph_text      = "subtext"
proc_misc       = "mauve"
cpu_box         = "sapphire"
mem_box         = "green"
net_box         = "red"
proc_box        = "teal"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "teal"
cpu_mid         = "sapphire"
cpu_end         = "red"
free_start      = "mauve"
free_mid        = "sapphire"
free_end        = "blue"
cached_start    = "teal"
cached_mid      = "sky"
cached_end      = "red"
available_start = "green"
available_mid   = "yellow"
available_end   = "red"
used_start      = "green"
used_mid        = "yellow"
used_end        = "red"
download_start  = "teal"
download_mid    = "sapphire"
download_end    = "red"
upload_start    = "green"
upload_mid      = "yellow"
upload_end      = "red"
process_start   = "teal"
process_mid     = "sapphire"
process_end     = "mauve"
replace_mode    = "teal"
visual_mode     = "mauve"
dir_fg          = "sapphire"
git_fg          = "mauve"
time_fg         = "yellow"
