display_name = "Vesper"

[vars]
ghostty = "Vesper"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "orange"
color_scheme = "prefer-dark"

[palette]
base     = "#101010"
mantle   = "#0a0a0a"
surface  = "#2a2a2a"
overlay  = "#505050"
muted    = "#505050"
text     = "#ffffff"
subtext  = "#a0a0a0"
red      = "#ff8080"
orange   = "#ffc799"
yellow   = "#ffc799"
green    = "#99ffe4"
teal     = "#99ffe4"
sky      = "#99ffe4"
sapphire = "#99ffe4"
blue     = "#99ffe4"
mauve    = "#ffd7d7"

[colors]
highlight       = "orange"
secondary       = "green"
title           = "subtext"
hi_fg           = "orange"
selected_fg     = "text"
graph_text      = "subtext"
proc_misc       = "green"
cpu_box         = "orange"
mem_box         = "green"
net_box         = "red"
proc_box        = "teal"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "orange"
cpu_start       = "green"
cpu_mid         = "orange"
cpu_end         = "red"
free_start      = "green"
free_mid        = "teal"
free_end        = "orange"
cached_start    = "green"
cached_mid      = "teal"
cached_end      = "sky"
available_start = "green"
available_mid   = "orange"
available_end   = "red"
used_start      = "green"
used_mid        = "orange"
used_end        = "red"
download_start  = "green"
download_mid    = "teal"
download_end    = "sky"
upload_start    = "teal"
upload_mid      = "orange"
upload_end      = "red"
process_start   = "green"
process_mid     = "orange"
process_end     = "teal"
replace_mode    = "teal"
visual_mode     = "overlay"
dir_fg          = "orange"
git_fg          = "green"
time_fg         = "muted"
