display_name = "Matte Black"

[vars]
ghostty = "Matte Black"

[nvim]
strategy = "luafile"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "orange"
color_scheme = "prefer-dark"

[palette]
base     = "#121212"
mantle   = "#0a0a0a"
surface  = "#333333"
overlay  = "#4a4a4a"
muted    = "#8a8a8d"
text     = "#bebebe"
subtext  = "#eaeaea"
red      = "#D35F5F"
orange   = "#e68e0d"
yellow   = "#FFC107"
green    = "#FFC107"
teal     = "#bebebe"
sky      = "#eaeaea"
sapphire = "#f59e0b"
blue     = "#f59e0b"
mauve    = "#D35F5F"

[colors]
highlight       = "orange"
secondary       = "yellow"
title           = "subtext"
hi_fg           = "orange"
selected_fg     = "subtext"
graph_text      = "text"
proc_misc       = "orange"
cpu_box         = "orange"
mem_box         = "yellow"
net_box         = "red"
proc_box        = "muted"
div_line        = "overlay"
temp_start      = "yellow"
temp_mid        = "orange"
cpu_start       = "yellow"
cpu_mid         = "orange"
cpu_end         = "red"
free_start      = "yellow"
free_mid        = "orange"
free_end        = "red"
cached_start    = "yellow"
cached_mid      = "orange"
cached_end      = "red"
available_start = "yellow"
available_mid   = "orange"
available_end   = "red"
used_start      = "yellow"
used_mid        = "orange"
used_end        = "red"
download_start  = "yellow"
download_mid    = "orange"
download_end    = "red"
upload_start    = "yellow"
upload_mid      = "orange"
upload_end      = "red"
process_start   = "yellow"
process_mid     = "orange"
process_end     = "red"
success_status  = "yellow"
replace_mode    = "orange"
visual_mode     = "muted"
dir_fg          = "orange"
git_fg          = "yellow"
time_fg         = "muted"
