display_name = "Kanagawa"

[vars]
ghostty = "Kanagawabones"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Kanagawa"
shell_theme = "Kanagawa"
icon_theme = "Papirus-Dark"
accent_color = "red"

[palette]
base     = "#1f1f28"
mantle   = "#16161d"
surface  = "#223249"
overlay  = "#727169"
muted    = "#727169"
text     = "#dcd7ba"
subtext  = "#c8c093"
red      = "#e82424"
orange   = "#ffa066"
yellow   = "#e6c384"
green    = "#98bb6c"
teal     = "#7aa89f"
sky      = "#7fb4ca"
sapphire = "#7e9cdb"
blue     = "#7e9cdb"
mauve    = "#957fbb"

[colors]
highlight       = "red"
secondary       = "yellow"
title           = "text"
hi_fg           = "red"
selected_fg     = "orange"
inactive_fg     = "overlay"
graph_text      = "text"
proc_misc       = "teal"
cpu_box         = "overlay"
mem_box         = "overlay"
net_box         = "overlay"
proc_box        = "overlay"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "orange"
cpu_start       = "green"
cpu_mid         = "orange"
cpu_end         = "red"
free_start      = "teal"
free_mid        = "teal"
free_end        = "red"
cached_start    = "yellow"
cached_mid      = "orange"
cached_end      = "orange"
available_start = "mauve"
available_mid   = "mauve"
available_end   = "sky"
used_start      = "teal"
used_mid        = "sapphire"
used_end        = "sky"
download_start  = "sapphire"
download_mid    = "mauve"
download_end    = "mauve"
upload_start    = "orange"
upload_mid      = "yellow"
upload_end      = "red"
process_start   = "green"
process_mid     = "orange"
process_end     = "red"
replace_mode    = "orange"
visual_mode     = "mauve"
dir_fg          = "sapphire"
git_fg          = "teal"
time_fg         = "yellow"
