display_name = "Catppuccin Macchiato"

[vars]
ghostty = "Catppuccin Macchiato"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Catppuccin-Mocha-Standard-Mauve-Dark"
shell_theme = "Catppuccin-Mocha-Standard-Mauve-Dark"
icon_theme = "Papirus-Dark"
accent_color = "purple"

[palette]
base     = "#24273a"
mantle   = "#1e2030"
surface  = "#51576d"
overlay  = "#737994"
muted    = "#838ba7"
text     = "#c6d0f5"
subtext  = "#b8c0e0"
red      = "#e78284"
orange   = "#ef9f76"
yellow   = "#e5c890"
green    = "#a6d189"
teal     = "#81c8be"
sky      = "#99d1db"
sapphire = "#85c1dc"
blue     = "#8caaee"
mauve    = "#ca9ee6"

[colors]
highlight       = "teal"
secondary       = "subtext"
title           = "text"
hi_fg           = "blue"
selected_fg     = "blue"
graph_text      = "subtext"
proc_misc       = "subtext"
cpu_box         = "mauve"
mem_box         = "green"
net_box         = "red"
proc_box        = "blue"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "teal"
cpu_mid         = "sapphire"
cpu_end         = "red"
free_start      = "green"
free_mid        = "subtext"
free_end        = "blue"
cached_start    = "sapphire"
cached_mid      = "blue"
cached_end      = "red"
available_start = "green"
available_mid   = "red"
available_end   = "red"
used_start      = "teal"
used_mid        = "teal"
used_end        = "sky"
download_start  = "orange"
download_mid    = "red"
download_end    = "red"
upload_start    = "green"
upload_mid      = "teal"
upload_end      = "sky"
process_start   = "sapphire"
process_mid     = "subtext"
process_end     = "mauve"
replace_mode    = "teal"
visual_mode     = "overlay"
dir_fg          = "teal"
git_fg          = "mauve"
time_fg         = "yellow"
