display_name = "Nord"

[vars]
ghostty = "Nord"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Nordic-darker"
shell_theme = "Nordic-darker"
icon_theme = "Papirus-Dark"
accent_color = "blue"

[palette]
base     = "#2e3440"
mantle   = "#242932"
surface  = "#3b4252"
overlay  = "#434c5e"
muted    = "#4c566a"
text     = "#d8dee9"
subtext  = "#e5e9f0"
red      = "#bf616a"
orange   = "#d08770"
yellow   = "#ebcb8b"
green    = "#a3be8c"
teal     = "#8fbcbb"
sky      = "#88c0d0"
sapphire = "#81a1c1"
blue     = "#5e81ac"
mauve    = "#b48ead"

[colors]
highlight       = "blue"
secondary       = "teal"
title           = "teal"
hi_fg           = "blue"
selected_bg     = "muted"
selected_fg     = "subtext"
graph_text      = "text"
meter_bg        = "muted"
proc_misc       = "blue"
cpu_box         = "muted"
mem_box         = "muted"
net_box         = "muted"
proc_box        = "muted"
div_line        = "muted"
temp_start      = "sapphire"
temp_mid        = "sky"
cpu_start       = "sapphire"
cpu_mid         = "sky"
cpu_end         = "subtext"
free_start      = "sapphire"
free_mid        = "sky"
free_end        = "red"
cached_start    = "sapphire"
cached_mid      = "sky"
cached_end      = "subtext"
available_start = "sapphire"
available_mid   = "sky"
available_end   = "red"
used_start      = "sapphire"
used_mid        = "sky"
used_end        = "red"
download_start  = "sapphire"
download_mid    = "sky"
download_end    = "red"
upload_start    = "sapphire"
upload_mid      = "sky"
upload_end      = "red"
process_start   = "sapphire"
process_mid     = "sky"
process_end     = "red"
success_status  = "teal"
replace_mode    = "sky"
visual_mode     = "muted"
dir_fg          = "blue"
git_fg          = "teal"
time_fg         = "yellow"
