display_name = "Monokai Pro"

[vars]
ghostty = "Monokai Pro"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "green"
color_scheme = "prefer-dark"

[palette]
base     = "#2d2a2e"
mantle   = "#1e1f1c"
surface  = "#3e3d32"
overlay  = "#75715e"
muted    = "#49483e"
text     = "#f8f8f2"
subtext  = "#f8f8f0"
red      = "#f92672"
orange   = "#fd971f"
yellow   = "#e6db74"
green    = "#a6e22e"
teal     = "#66d9ef"
sky      = "#66d9ef"
sapphire = "#66d9ef"
blue     = "#819aff"
mauve    = "#ae81ff"

[colors]
highlight       = "green"
secondary       = "teal"
title           = "subtext"
hi_fg           = "green"
selected_fg     = "text"
inactive_fg     = "overlay"
graph_text      = "text"
proc_misc       = "teal"
cpu_box         = "green"
mem_box         = "teal"
net_box         = "red"
proc_box        = "mauve"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "green"
cpu_mid         = "teal"
cpu_end         = "red"
free_start      = "green"
free_mid        = "teal"
free_end        = "mauve"
cached_start    = "teal"
cached_mid      = "sky"
cached_end      = "mauve"
available_start = "green"
available_mid   = "yellow"
available_end   = "orange"
used_start      = "green"
used_mid        = "yellow"
used_end        = "red"
download_start  = "teal"
download_mid    = "mauve"
download_end    = "red"
upload_start    = "green"
upload_mid      = "orange"
upload_end      = "red"
process_start   = "green"
process_mid     = "teal"
process_end     = "mauve"
replace_mode    = "teal"
visual_mode     = "overlay"
dir_fg          = "green"
git_fg          = "teal"
time_fg         = "yellow"
