display_name = "Vantablack"

[vars]
ghostty = "vantablack"

[nvim]
strategy = "luafile"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "slate"
color_scheme = "prefer-dark"

[palette]
base     = "#000000"
mantle   = "#000000"
surface  = "#fdfdfd"
overlay  = "#5a5a5a"
muted    = "#8d8d8d"
text     = "#ffffff"
subtext  = "#ececec"
red      = "#a4a4a4"
orange   = "#a4a4a4"
yellow   = "#cecece"
green    = "#b6b6b6"
teal     = "#b0b0b0"
sky      = "#b0b0b0"
sapphire = "#8d8d8d"
blue     = "#8d8d8d"
mauve    = "#9b9b9b"

[colors]
highlight       = "subtext"
secondary       = "muted"
title           = "text"
hi_fg           = "subtext"
selected_bg     = "overlay"
selected_fg     = "text"
graph_text      = "subtext"
meter_bg        = "overlay"
proc_misc       = "subtext"
cpu_box         = "muted"
mem_box         = "muted"
net_box         = "muted"
proc_box        = "muted"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
temp_end        = "subtext"
cpu_start       = "green"
cpu_mid         = "teal"
cpu_end         = "subtext"
free_start      = "green"
free_mid        = "muted"
free_end        = "subtext"
cached_start    = "green"
cached_mid      = "teal"
cached_end      = "subtext"
available_start = "green"
available_mid   = "muted"
available_end   = "subtext"
used_start      = "green"
used_mid        = "teal"
used_end        = "subtext"
download_start  = "green"
download_mid    = "teal"
download_end    = "subtext"
upload_start    = "green"
upload_mid      = "muted"
upload_end      = "subtext"
process_start   = "green"
process_mid     = "teal"
process_end     = "subtext"
error_status    = "subtext"
replace_mode    = "overlay"
visual_mode     = "muted"
dir_fg          = "subtext"
git_fg          = "muted"
time_fg         = "muted"
