display_name = "Dracula"

[vars]
ghostty = "Dracula"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Dracula"
shell_theme = "Dracula"
icon_theme = "Papirus-Dark"
accent_color = "purple"

[palette]
base     = "#282a36"
mantle   = "#21222c"
surface  = "#44475a"
overlay  = "#6272a4"
muted    = "#44475a"
text     = "#f8f8f2"
subtext  = "#f8f8f2"
red      = "#ff5555"
orange   = "#ffb86c"
yellow   = "#f1fa8c"
green    = "#50fa7b"
teal     = "#8be9fd"
sky      = "#8be9fd"
sapphire = "#6272a4"
blue     = "#6272a4"
mauve    = "#bd93f9"

[colors]
highlight       = "mauve"
secondary       = "green"
title           = "text"
hi_fg           = "sapphire"
selected_bg     = "mauve"
selected_fg     = "text"
inactive_fg     = "surface"
graph_text      = "text"
proc_misc       = "mauve"
cpu_box         = "mauve"
mem_box         = "green"
net_box         = "red"
proc_box        = "teal"
div_line        = "surface"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "teal"
cpu_mid         = "yellow"
cpu_end         = "red"
free_start      = "mauve"
free_mid        = "teal"
free_end        = "mauve"
cached_start    = "teal"
cached_mid      = "sky"
cached_end      = "mauve"
available_start = "orange"
available_mid   = "yellow"
available_end   = "orange"
used_start      = "green"
used_mid        = "yellow"
used_end        = "red"
download_start  = "teal"
download_mid    = "mauve"
download_end    = "mauve"
upload_start    = "green"
upload_mid      = "yellow"
upload_end      = "red"
process_start   = "teal"
process_mid     = "mauve"
process_end     = "red"
replace_mode    = "surface"
visual_mode     = "mauve"
dir_fg          = "teal"
git_fg          = "mauve"
time_fg         = "orange"
