display_name = "Osaka Jade"

[vars]
ghostty = "Osaka Jade"

[nvim]
strategy = "luafile"

[gnome]
gtk_theme = "Adwaita-dark"
shell_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
accent_color = "green"
color_scheme = "prefer-dark"

[palette]
base     = "#111c18"
mantle   = "#0a1410"
surface  = "#23372B"
overlay  = "#53685B"
muted    = "#53685B"
text     = "#C1C497"
subtext  = "#F6F5DD"
red      = "#FF5345"
orange   = "#db9f9c"
yellow   = "#E5C736"
green    = "#549e6a"
teal     = "#2DD5B7"
sky      = "#8CD3CB"
sapphire = "#509475"
blue     = "#ACD4CF"
mauve    = "#D2689C"

[colors]
highlight       = "sapphire"
secondary       = "teal"
title           = "subtext"
hi_fg           = "sapphire"
selected_fg     = "subtext"
graph_text      = "text"
proc_misc       = "teal"
cpu_box         = "sapphire"
mem_box         = "green"
net_box         = "red"
proc_box        = "teal"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "green"
cpu_mid         = "sapphire"
cpu_end         = "red"
free_start      = "teal"
free_mid        = "sapphire"
free_end        = "red"
cached_start    = "teal"
cached_mid      = "sky"
cached_end      = "red"
available_start = "green"
available_mid   = "yellow"
available_end   = "red"
used_start      = "green"
used_mid        = "sapphire"
used_end        = "red"
download_start  = "teal"
download_mid    = "sapphire"
download_end    = "red"
upload_start    = "green"
upload_mid      = "sapphire"
upload_end      = "red"
process_start   = "green"
process_mid     = "teal"
process_end     = "sapphire"
replace_mode    = "teal"
visual_mode     = "mauve"
dir_fg          = "sapphire"
git_fg          = "teal"
time_fg         = "yellow"
