display_name = "Everforest"

[vars]
ghostty = "Everforest Dark"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Everforest-Dark-BL"
shell_theme = "Everforest-Dark-BL"
icon_theme = "Papirus-Dark"
accent_color = "green"

[palette]
base     = "#2d353b"
mantle   = "#272e33"
surface  = "#3d484d"
overlay  = "#475258"
muted    = "#3d484d"
text     = "#d3c6aa"
subtext  = "#d3c6aa"
red      = "#f85552"
orange   = "#e69875"
yellow   = "#dbbc7f"
green    = "#a7c080"
teal     = "#7fbbb3"
sky      = "#83c092"
sapphire = "#7fbbb3"
blue     = "#e67e80"
mauve    = "#d699b6"

[colors]
highlight       = "blue"
secondary       = "orange"
title           = "text"
hi_fg           = "blue"
selected_fg     = "yellow"
graph_text      = "text"
proc_misc       = "green"
cpu_box         = "surface"
mem_box         = "surface"
net_box         = "surface"
proc_box        = "surface"
div_line        = "surface"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "green"
cpu_mid         = "yellow"
cpu_end         = "red"
free_start      = "green"
free_mid        = "yellow"
free_end        = "green"
cached_start    = "teal"
cached_mid      = "sky"
cached_end      = "green"
available_start = "red"
available_mid   = "yellow"
available_end   = "green"
used_start      = "green"
used_mid        = "yellow"
used_end        = "red"
download_start  = "green"
download_mid    = "sky"
download_end    = "teal"
upload_start    = "yellow"
upload_mid      = "orange"
upload_end      = "blue"
process_start   = "green"
process_mid     = "blue"
process_end     = "red"
replace_mode    = "surface"
visual_mode     = "teal"
dir_fg          = "blue"
git_fg          = "text"
time_fg         = "yellow"
