display_name = "Catppuccin Mocha"

[vars]
ghostty = "Catppuccin Mocha"

[gnome]
gtk_theme = "Catppuccin-Mocha-Standard-Blue-Dark"
shell_theme = "Catppuccin-Mocha-Standard-Blue-Dark"
icon_theme = "Papirus-Dark"
accent_color = "purple"
color_scheme = "prefer-dark"

[palette]
base     = "#1e1e2e"
mantle   = "#181825"
surface  = "#585b70"
overlay  = "#6c7086"
muted    = "#45475a"
text     = "#cdd6f4"
subtext  = "#bac2de"
red      = "#f38ba8"
orange   = "#fab387"
yellow   = "#f9e2af"
green    = "#a6e3a1"
teal     = "#94e2d5"
sky      = "#89dceb"
sapphire = "#74c7ec"
blue     = "#89b4fa"
mauve    = "#cba6f7"

[colors]
highlight       = "blue"
secondary       = "mauve"
title           = "text"
hi_fg           = "blue"
selected_fg     = "blue"
graph_text      = "subtext"
proc_misc       = "subtext"
cpu_box         = "mauve"
mem_box         = "green"
net_box         = "red"
proc_box        = "blue"
div_line        = "overlay"
temp_start      = "green"
temp_mid        = "yellow"
cpu_start       = "teal"
cpu_mid         = "sapphire"
cpu_end         = "red"
free_start      = "mauve"
free_mid        = "subtext"
free_end        = "blue"
cached_start    = "sapphire"
cached_mid      = "blue"
cached_end      = "red"
available_start = "orange"
available_mid   = "red"
available_end   = "red"
used_start      = "green"
used_mid        = "teal"
used_end        = "red"
download_start  = "teal"
download_mid    = "blue"
download_end    = "red"
upload_start    = "green"
upload_mid      = "teal"
upload_end      = "red"
process_start   = "sapphire"
process_mid     = "subtext"
process_end     = "mauve"
replace_mode    = "teal"
visual_mode     = "overlay"
dir_fg          = "blue"
git_fg          = "mauve"
time_fg         = "yellow"
