display_name = "Nightfox"

[vars]
ghostty = "Nightfox"

[gnome]
color_scheme = "prefer-dark"
gtk_theme = "Nordic-darker"
shell_theme = "Nordic-darker"
icon_theme = "Papirus-Dark"
accent_color = "teal"

[palette]
base     = "#192330"
mantle   = "#131a24"
surface  = "#393b44"
overlay  = "#393b44"
muted    = "#393b44"
text     = "#cdcecf"
subtext  = "#dfdfe0"
red      = "#c94f6d"
orange   = "#f4a261"
yellow   = "#dbc074"
green    = "#81b29a"
teal     = "#63cdcf"
sky      = "#86abdc"
sapphire = "#81a1c1"
blue     = "#719cd6"
mauve    = "#9d79d6"

[colors]
highlight       = "blue"
secondary       = "yellow"
title           = "green"
hi_fg           = "sky"
selected_fg     = "subtext"
inactive_fg     = "surface"
graph_text      = "subtext"
proc_misc       = "sky"
cpu_box         = "surface"
mem_box         = "surface"
net_box         = "surface"
proc_box        = "surface"
div_line        = "surface"
temp_start      = "sapphire"
temp_mid        = "sky"
cpu_start       = "sapphire"
cpu_mid         = "sky"
cpu_end         = "red"
free_start      = "sapphire"
free_mid        = "sky"
free_end        = "red"
cached_start    = "sapphire"
cached_mid      = "sky"
cached_end      = "red"
available_start = "sapphire"
available_mid   = "sky"
available_end   = "red"
used_start      = "sapphire"
used_mid        = "sky"
used_end        = "red"
download_start  = "sapphire"
download_mid    = "sky"
download_end    = "red"
upload_start    = "sapphire"
upload_mid      = "sky"
upload_end      = "red"
process_start   = "sapphire"
process_mid     = "sky"
process_end     = "red"
replace_mode    = "mauve"
visual_mode     = "yellow"
dir_fg          = "blue"
git_fg          = "green"
time_fg         = "yellow"
